// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: (c) 2025 Ci4Rail GmbH

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.0--rc2
// source: eeinv.proto

package eeinv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       string                 `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`                                // e.g. S101-CPU01-00001
	MajorVersion  uint32                 `protobuf:"varint,2,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"` // e.g. 0
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`                                  // typically UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_eeinv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_eeinv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_eeinv_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetArticle() string {
	if x != nil {
		return x.Article
	}
	return ""
}

func (x *Inventory) GetMajorVersion() uint32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *Inventory) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

var File_eeinv_proto protoreflect.FileDescriptor

const file_eeinv_proto_rawDesc = "" +
	"\n" +
	"\veeinv.proto\x12\x05eeinv\"b\n" +
	"\tInventory\x12\x18\n" +
	"\aarticle\x18\x01 \x01(\tR\aarticle\x12#\n" +
	"\rmajor_version\x18\x02 \x01(\rR\fmajorVersion\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serialB\tZ\a./eeinvb\x06proto3"

var (
	file_eeinv_proto_rawDescOnce sync.Once
	file_eeinv_proto_rawDescData []byte
)

func file_eeinv_proto_rawDescGZIP() []byte {
	file_eeinv_proto_rawDescOnce.Do(func() {
		file_eeinv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eeinv_proto_rawDesc), len(file_eeinv_proto_rawDesc)))
	})
	return file_eeinv_proto_rawDescData
}

var file_eeinv_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_eeinv_proto_goTypes = []any{
	(*Inventory)(nil), // 0: eeinv.Inventory
}
var file_eeinv_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eeinv_proto_init() }
func file_eeinv_proto_init() {
	if File_eeinv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eeinv_proto_rawDesc), len(file_eeinv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eeinv_proto_goTypes,
		DependencyIndexes: file_eeinv_proto_depIdxs,
		MessageInfos:      file_eeinv_proto_msgTypes,
	}.Build()
	File_eeinv_proto = out.File
	file_eeinv_proto_goTypes = nil
	file_eeinv_proto_depIdxs = nil
}
